### ISSUE TITLE
[0.3.0.pre] pik <command> -h or --help NoMethodError failures

### ISSUE THREAD

**Issue by jonforums** [vertiginous/pik#103] opened 2011-01-26 19:45 UTC
On the 0.3.0.pre 2nd download, I get

<pre>
C:\Users\Jon\Documents>pik --version
pik 0.3.0.pre on Microsoft Windows [Version 6.1.7600]
by Gordon Thiesfeld (gthiesfeld@gmail.com)

C:\Users\Jon\Documents>pik alias -h
Usage: pik alias [options]

manages aliases for ruby versions

    -V, --version                    Pik version
    -d, --debug                      Outputs debug information
pik_runner:34: undefined method `close' for Pik::Alias:Class (NoMethodError)

C:\Users\Jon\Documents>pik alias --help
Usage: pik alias [options]

manages aliases for ruby versions

    -V, --version                    Pik version
    -d, --debug                      Outputs debug information
pik_runner:34: undefined method `close' for Pik::Alias:Class (NoMethodError)
</pre>

**Comment by vertiginous** [comment] 2011-01-26 21:03
This is a foible of optparse.  I'll fix it so it doesn't throw an exception, but the documented way to view help for a command is.

```
 pik help alias
```

**Comment by jonforums** [comment] 2011-01-26 21:49
Understood...forgot to mention in the first post that in 0.2.8 both -h and --help work without issue.

FWIW, I like http://trollop.rubyforge.org/ over optparse. I haven't used highline so I don't know how they would work together. I do like that trollop is one file and can simply be vendored in your lib/ dir.

**Comment by vertiginous** [comment] 2011-01-26 21:52
I've been meaning to take a better look at trollop.  Maybe when i get some more free time...

**Comment by vertiginous** [comment] 2011-01-26 22:00
Ahh!  This was a regression caused by my bad habit of reusing variable names.

**Comment by vertiginous** [comment] 2011-03-03 06:08
fixed, closing.

**Closed as completed by vertiginous** 2011-03-03 06:08 UTC
