### ISSUE TITLE
switching version creates 'lib' directory

### ISSUE THREAD

**Issue by semmons99** [vertiginous/pik#53] opened 2010-03-24 15:50 UTC
Whenever I switch versions, a new directory is created (c:\lib\ruby\gems). I guessing this has something to do with GEM_PATH and GEM_HOME, neither of which are set in my configs.

**Comment by macler** [comment] 2010-05-02 16:24
Switching doesn't work under Vista x64. When I try to switch then c:\lib is created.

**Comment by luislavena** [comment] 2010-05-06 13:49
To confirm this, the issue is RubyGems 1.3.5, used by Pik internally. This has been solved with newer RubyGems.

**Comment by vertiginous** [comment] 2010-06-09 21:23
I've switched from rubygems to crown.

Fixed in dfc8e31d438846493404

**Closed as completed by vertiginous** 2010-06-09 21:23 UTC
