### ISSUE TITLE
Error: can't dup NilClass

### ISSUE THREAD

**Issue by SeanJA** [vertiginous/pik#79] opened 2010-09-21 05:57 UTC
I got the following when I installed pik and tried to run it:

`There was an error.
 Error: can't dup NilClass

  in: pathname.rb:205:in 'dup'
  in: pathname.rb:205:in 'initialize'
  in: pik/commands/add_command.rb:17:in 'new'
  in: pik/commands/add_command.rb:17:in 'add'
  in: pik/commands/add_command.rb:13:in 'execute'
  in: pik_runner:27`

Turns out that you have to have a version of ruby installed to run pik I guess?
That fixed the error anyway...

**Comment by chulan** [comment] 2010-09-28 17:32
I got the same issue, resolved the same way
On WinXp, using the MSI for pik 0.2.8

**Comment by vertiginous** [comment] 2011-01-24 17:18
Should be fixed in 0.3.0.pre

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b

This is a duplicate of #71. Please comment there. Closing.

**Closed as completed by vertiginous** 2011-01-24 17:18 UTC
