### ISSUE TITLE
RubyGems plugins fire missing files in RubyGems itself (exerb executable)

### ISSUE THREAD

**Issue by luislavena** [vertiginous/pik#37] opened 2009-11-11 14:28 UTC
If default Ruby had installed either gemcutter or open_gem plugins, it fires errors due missing files:

<pre><code>
rubygems/custom_require.rb:31:in `gem_original_require': No such file to load -- rubygems/local_remote_options (LoadError)
        from rubygems/custom_require.rb:31:in `require'
        from C:/Users/Luis/.gem/ruby/1.8/gems/gemcutter-0.1.6/lib/commands/abstract_command.rb:1
        from rubygems/custom_require.rb:31:in `gem_original_require'
        from rubygems/custom_require.rb:31:in `require'
        from C:/Users/Luis/.gem/ruby/1.8/gems/gemcutter-0.1.6/lib/rubygems_plugin.rb:4
        from rubygems.rb:1136:in `load'
        from rubygems.rb:1136
        from rubygems.rb:1134:in `each'
        from rubygems.rb:1134
</code></pre>

<pre><code>
C:\Users\Luis\Projects\oss\oci>pik
rubygems/custom_require.rb:31:in `gem_original_require': No such file to load -- rubygems/version_option (LoadError)
        from rubygems/custom_require.rb:31:in `require'
        from C:/Users/Luis/.gem/ruby/1.8/gems/open_gem-1.4.0/lib/rubygems_plugin.rb:5
        from rubygems.rb:1136:in `load'
        from rubygems.rb:1136
        from rubygems.rb:1134:in `each'
        from rubygems.rb:1134
</code></pre>

A workaround could be require those files manually after require 'rubygems'

**Comment by vertiginous** [comment] 2009-11-11 18:06
I can't reproduce this.  It shouldn't be interacting with your GEM_HOME like that.  Could your run:

<pre><code>

> pik info -v & pik run which --all pik.bat
> </pre></code>

**Comment by luislavena** [comment] 2009-11-11 19:14
Yup, I keep using GEM_HOME and GEM_PATH to avoid gems being installed inside each Ruby Installation.

**Comment by vertiginous** [comment] 2009-11-11 19:27
Pik will unset these internally before requiring rubygems. 

http://github.com/vertiginous/pik/blob/master/lib/pik.rb#L7

That's why I'm confused.

**Comment by luislavena** [comment] 2009-11-11 19:33
Pik info -v:

<pre><code>
C:\Users\Luis>pik info -v
pik 0.2.6
pik 0.2.6

ruby:
interpreter:  "ruby"
version:      "1.8.6"
date:         "2009-08-04"
platform:     "i386-mingw32"
patchlevel:   "383"
full_version: "ruby 1.8.6 (2009-08-04 patchlevel 383) [i386-mingw32]"

homes:
gem:          "C:\Users\Luis\Tools\Ruby\ruby-1.8.6-p383-i386-mingw32\lib\ruby\gems\1.8"
ruby:         "C:\Users\Luis\Tools\Ruby\ruby-1.8.6-p383-i386-mingw32"

binaries:
ruby:         "C:\Users\Luis\Tools\Ruby\ruby-1.8.6-p383-i386-mingw32\bin\ruby.exe"
irb:          "C:\Users\Luis\Tools\Ruby\ruby-1.8.6-p383-i386-mingw32\bin\irb.bat"
gem:          "C:\Users\Luis\Tools\Ruby\ruby-1.8.6-p383-i386-mingw32\bin\gem.bat"
rake:         "C:\Users\Luis\.gem\ruby\1.8\bin\rake.bat"

environment:
GEM_HOME:     ""
HOME:         "C:\Users\Luis"
IRBRC:        ""
RUBYOPT:      ""

file associations:
.rb:
.rbw:
</code></pre>


Note GEM_HOME and GEM_PATH are set outside (using SET):

<pre><code>
C:\Users\Luis>set GEM
GEM_HOME=C:\Users\Luis\.gem\ruby\1.8
GEM_PATH=C:\Users\Luis\.gem\ruby\1.8
</code></pre>


Now, after installed the open_gem or gemcutter gems:

<pre><code>
C:\Users\Luis>pik info -v
rubygems/custom_require.rb:31:in `gem_original_require': No such file to load -- rubygems/local_remote_options (LoadError)
        from rubygems/custom_require.rb:31:in `require'
        from C:/Users/Luis/.gem/ruby/1.8/gems/gemcutter-0.1.6/lib/commands/abstract_command.rb:1
        from rubygems/custom_require.rb:31:in `gem_original_require'
        from rubygems/custom_require.rb:31:in `require'
        from C:/Users/Luis/.gem/ruby/1.8/gems/gemcutter-0.1.6/lib/rubygems_plugin.rb:4
        from rubygems.rb:1136:in `load'
        from rubygems.rb:1136
        from rubygems.rb:1134:in `each'
        from rubygems.rb:1134
</code></pre>

**Comment by vertiginous** [comment] 2009-11-11 21:56
I had gemcutter install, but wasn't seeing this.  I installed open_gem, and now I'm getting the same error.  It doesn't matter if I use GEM_HOME and GEM_PATH or not.

I think I'll have to dig into rubygems internals and see if I can stop this.  Otherwise any gem plugin on a user's system could break pik.

**Comment by vertiginous** [comment] 2009-11-11 22:00
I take that back. I used the default location for GEM_HOME, ie. "C:\Documents and Settings\gthiesfeld.gem\ruby\1.8".  That's why I was seeing the error whether or not the env vars were set.  It will check there regardless of where ruby is installed, or if the env vars are set.

**Comment by luislavena** [comment] 2009-11-11 22:21
Is a issue with RubyGems itself, something considered a feature.

See this ticket with my request with the links to the mailing list post:

http://rubyforge.org/tracker/index.php?func=detail&aid=27422&group_id=126&atid=578

**Comment by vertiginous** [comment] 2009-11-11 22:32
I can work around it by setting a "fake" home when I require rubygems, then resetting it immediately afterwards.  Setting ENV['HOME'] to nil will cause it to use another dir for Gem.user_home.

http://gist.github.com/232377

I don't like it at all, though.

**Comment by vertiginous** [comment] 2010-06-09 02:03
I think I'll stop using rubygems, and use crown instead.

http://github.com/vjoel/crown

**Comment by vertiginous** [comment] 2010-06-09 21:01
Fixed in dfc8e31d438846493404

**Closed as completed by vertiginous** 2010-06-09 21:01 UTC
Labels: Bug
