### ISSUE TITLE
After install running pik fails, Windows Vista SP2

### ISSUE THREAD

**Issue by tbondy760** [vertiginous/pik#75] opened 2010-08-19 11:41 UTC
C:\Users\Dad>pik

There was an error.
 Error: can't dup NilClass

  in: pathname.rb:205:in `dup'

  in: pathname.rb:205:in `initialize'

  in: pik/commands/add_command.rb:17:in `new'

  in: pik/commands/add_command.rb:17:in `add'

  in: pik/commands/add_command.rb:13:in `execute'

  in: pik_runner:27

C:\Users\Dad>

pik was installed using 
 msiexec /i http://github.com/downloads/vertiginous/pik/pik-0.2.8.msi

before Ruby was installed.

**Comment by luislavena** [comment] 2010-08-20 00:19
Have you added Ruby to your pik installation? `pik add`

pik without arguments fails because there is no Ruby version available.

**Comment by voxik** [comment] 2010-08-26 23:25
I believe that this issues was fixed by this commit: http://github.com/vertiginous/pik/commit/02e2ff306b68170a878ca8c4691016cba07600ae

**Comment by miau** [comment] 2011-01-06 16:37
02e2ff306b68170a878ca8c4691016cba07600ae doesn't solve this problem.

My workaround to avoid this error is creating %USERPROFILE%.pik\config.yml by hand.

<pre>
--- 
"000: ruby 0.0.0 (dummy ruby for pik)": 
  :path: !ruby/object:Pathname 
    path: C:/pik/dummy
--- {}
</pre>


Since msi installer is for a machine that doesn't have ruby installed, running without ruby installation would be appreciated.

#79 may be the same problem.

**Comment by miau** [comment] 2011-01-06 17:06
I jumped to the wrong conclusion.
Although 02e2ff306b68170a878ca8c4691016cba07600ae might solve this problem, this commit is on June 26 and pik-0.2.8.msi was uploaded on June 21.

**Comment by vertiginous** [comment] 2011-01-24 17:17
Should be fixed in 0.3.0.pre

http://groups.google.com/group/discuss_pik/browse_thread/thread/ea94cb38d26ca92b

This is a duplicate of #71.  Please comment there.  Closing.

**Closed as completed by vertiginous** 2011-01-24 17:17 UTC
